In [33]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd

In [34]:
# Load the dataset
df = pd.read_csv('House price.csv')
print(df.head())

   Row  Rent ($)  Size (sq ft)  Distance to City Center (miles)  Year Built
0    1       800           400                               20        1980
1    2       850           450                               19        1982
2    3       900           500                               18        1984
3    4       950           550                               17        1986
4    5      1000           600                               16        1988


In [35]:
df_drop = df.drop(['Row','Year Built'], axis=1)

In [36]:
df_drop.head()

Rent ($)  Size (sq ft)  Distance to City Center (miles)
0       800           400                               20
1       850           450                               19
2       900           500                               18
3       950           550                               17
4      1000           600                               16

In [37]:
df_new = df_drop.dropna()

In [38]:
X = df_new.drop("Rent ($)", axis=1).values
y = df_new['Rent ($)'].values

In [39]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [40]:
# Define the model using TensorFlow and Keras
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [41]:
# Compile the model
model.compile(loss=tf.keras.losses.binary_crossentropy, optimizer="adam",
             metrics=[tf.keras.metrics.BinaryAccuracy(name='accuracy'),
                tf.keras.metrics.Precision(name='precision'),
                tf.keras.metrics.Recall(name='recall')])

In [42]:
# Train the model
model.fit(X_train, y_train, epochs=15, batch_size=10, verbose=1)

Epoch 1/15
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.0000e+00 - loss: -10782.9365 - precision: 0.6667 - recall: 0.2500     
Epoch 2/15
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: -283272.8438 - precision: 1.0000 - recall: 1.0000 
Epoch 3/15
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0000e+00 - loss: -529705.2500 - precision: 1.0000 - recall: 1.0000 
Epoch 4/15
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0000e+00 - loss: -793206.5625 - precision: 1.0000 - recall: 1.0000 
Epoch 5/15
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0000e+00 - loss: -1092009.2500 - precision: 1.0000 - recall: 1.0000
Epoch 6/15
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0000e+00 - loss: -1465285.6250 - precision: 1.0000 - recall: 1.0000 
Epoch 7/15
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0000e+00 - loss: -1890751.8750 - precision: 1.0000 - recall: 1.0000 
Epoch 8/15
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0000e+00 - loss: -2437

In [43]:
model.evaluate(X_test, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 340ms/step - accuracy: 0.0000e+00 - loss: -11333510.0000 - precision: 1.0000 - recall: 1.0000


[-11333510.0, 0.0, 1.0, 1.0]

In [44]:
# Evaluate the model
loss, accuracy, precision, recall = model.evaluate(X_test, y_test)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.0000e+00 - loss: -11333510.0000 - precision: 1.0000 - recall: 1.0000
Accuracy: 0.0
Precision: 1.0
Recall: 1.0


In [45]:
# Make predictions on the test set
y_test_pred = model.predict(X_test)
y_test_pred = tf.round(y_pred)
y_test_pred 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [46]:
# Generate the Confusion Matrix
print("Perceptron Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))

Perceptron Confusion Matrix:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]]
